### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by fristys** [pnp/generator-teams#46]
This generator doesn't seem to work (no matter the parameters) on macOS, but works fine on Windows:
![image](https://user-images.githubusercontent.com/1486500/47645413-39a98b00-db71-11e8-8762-06ddb486db2d.png)

```bash
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: s.addSyntheticLeadingComment is not a function
    at Function.insertTsExportDeclaration (/usr/local/lib/node_modules/generator-teams/generators/tab/index.js:1:1949)
    at e.TabGenerator.writing (/usr/local/lib/node_modules/generator-teams/generators/tab/index.js:1:4098)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-teams/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/generator-teams/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-teams/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-teams/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/local/lib/node_modules/generator-teams/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

Edit: This problem persists on both the `@master` and `@preview` versions

**Comment by cagdasdavulcu** [comment]
Hello,

Which node and npm  versions are you using? I tried it on my mac and it worked:
<img width="752" alt="screen shot 2018-11-02 at 23 38 52" src="https://user-images.githubusercontent.com/1059729/47943953-07918380-def9-11e8-9091-9e18503b288c.png">

Node Version: 8.2.1
Npm Version: 6.3.0

Regards,
Cagdas

**Comment by fristys** [comment]
The latest LTS (Node: 10.11; NPM: 6.4.1):
![image](https://user-images.githubusercontent.com/1486500/47949749-a0032480-df48-11e8-9d77-2d39f3139679.png)

Both your Node and NPM are fairly older versions. The latest (non LTS) version of node is 11

**Comment by cagdasdavulcu** [comment]
You're right! i upgraded the node and i got the following exception:
internal/modules/cjs/loader.js:582
    throw err;
    ^
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous>

This was the not same exception like yours, but i solved it using following commands:
npm cache clean --force
npm install -g typescript
npm install -g generator-teams@preview

Then it worked with Node Version: v10.13.0 and Npm Version: 6.4.1.

**Comment by wictorwilen** [comment]
Thanks @fristys for reporting this and @cagdasdavulcu  for helping out resolving it. @fristys  can you verify on your end that this is a viable resolution?

**Comment by CameronDwyer** [comment]
I ran into this issue as well, the particular dev machine I was on had:
node v8.12.0
npm 6.4.1

Just installing typescript globally was enough to get yo teams to work for me
npm install -g typescript

**Comment by wictorwilen** [comment]
Closing this as resolved. Feel free to open it again if the recommended solution does not work
